# syntax=docker/dockerfile:1
FROM golang:1.20-alpine AS build

WORKDIR /app-build
COPY go.mod go.sum ./
RUN go mod download

COPY cmd/ ./cmd
COPY internal/ ./internal 
COPY pkg/ ./pkg

RUN go build -o ./run_worker -v ./cmd/run_worker/

FROM alpine:latest
WORKDIR /app
COPY static_files/ /data/static_files
ARG GIT_VERSION
ENV STATIC_DIR_ROOT=/data DOCKERIZED=true VERSION_HASH=${GIT_VERSION}
VOLUME [ "/data" ]
COPY --from=build /app-build/run_worker /app/run_worker

CMD ["/app/run_worker"]